package views;

import entities.E_clients;
import business.B_clients;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LilJade
 */
public class V_clientCrud extends javax.swing.JDialog {

    int x, y;
    E_clients client = new E_clients();
    B_clients business = new B_clients();

    // Creates new form V_clientCrud
    public V_clientCrud(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cleanFields();
        blockFields();
        buttonsByDefault();

        showListClients();
    }

    public void showListClients() {
        String titles[] = {"Id", "Nombres", "Apellidos", "Telefono"};

        DefaultTableModel df = new DefaultTableModel(null, titles);

        ArrayList<E_clients> list = business.B_listClients();
        Iterator i = list.iterator();
        String rows[] = new String[4];

        while (i.hasNext()) {
            E_clients client;
            client = (E_clients) i.next();

            rows[0] = String.valueOf(client.getIdClient());
            rows[1] = client.getFirstName();
            rows[2] = client.getLastName();
            rows[3] = client.getNumberphone();

            df.addRow(rows);
        }

        tbClients.setModel(df);

        tbClients.getColumnModel().getColumn(0).setMaxWidth(25);
        tbClients.getColumnModel().getColumn(0).setMinWidth(25);
        tbClients.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(25);
        tbClients.getTableHeader().getColumnModel().getColumn(0).setMinWidth(25);
    }

    void cleanFields() {
        lblIdClient.setText("");
        txtFirstNameClient.setText("");
        txtLastNameClient.setText("");
        txtNumberPhoneClient.setText("");
    }

    void blockFields() {
        txtFirstNameClient.setEnabled(false);
        txtLastNameClient.setEnabled(false);
        txtNumberPhoneClient.setEnabled(false);
    }

    void unblockFields() {
        txtFirstNameClient.setEnabled(true);
        txtLastNameClient.setEnabled(true);
        txtNumberPhoneClient.setEnabled(true);
    }

    void buttonsByDefault() {
        btnNewClient.setEnabled(true);
        btnEditClient.setEnabled(false);
        btnDeleteClient.setEnabled(false);
        btnCancel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        lblTitleToMove = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTitleToMove1 = new javax.swing.JLabel();
        lblTitleToMove2 = new javax.swing.JLabel();
        lblTitleToMove3 = new javax.swing.JLabel();
        lblIdClient = new javax.swing.JLabel();
        txtFirstNameClient = new javax.swing.JTextField();
        txtLastNameClient = new javax.swing.JTextField();
        lblTitleToMove5 = new javax.swing.JLabel();
        txtNumberPhoneClient = new javax.swing.JTextField();
        lblTitleToMove6 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnDeleteClient = new javax.swing.JButton();
        btnEditClient = new javax.swing.JButton();
        btnNewClient = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClients = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(204, 0, 0));
        btnExit.setFont(new java.awt.Font("MADE TOMMY", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 90, 50));

        lblTitleToMove.setFont(new java.awt.Font("MADE TOMMY", 1, 36)); // NOI18N
        lblTitleToMove.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove.setText("Lista de Clientes");
        lblTitleToMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblTitleToMoveMouseDragged(evt);
            }
        });
        lblTitleToMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTitleToMoveMousePressed(evt);
            }
        });
        jPanel2.add(lblTitleToMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 710, 67));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitleToMove1.setFont(new java.awt.Font("MADE TOMMY", 1, 24)); // NOI18N
        lblTitleToMove1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleToMove1.setText("Configuración");

        lblTitleToMove2.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove2.setText("Nombres:");

        lblTitleToMove3.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove3.setText("ID: ");

        lblIdClient.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblIdClient.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFirstNameClient.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N

        txtLastNameClient.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N

        lblTitleToMove5.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove5.setText("Apellidos:");

        txtNumberPhoneClient.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        txtNumberPhoneClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumberPhoneClientKeyTyped(evt);
            }
        });

        lblTitleToMove6.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove6.setText("Numero de Teléfono");

        btnCancel.setBackground(new java.awt.Color(204, 0, 0));
        btnCancel.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDeleteClient.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteClient.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnDeleteClient.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteClient.setText("Borrar");
        btnDeleteClient.setBorder(null);
        btnDeleteClient.setBorderPainted(false);
        btnDeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClientActionPerformed(evt);
            }
        });

        btnEditClient.setBackground(new java.awt.Color(255, 153, 0));
        btnEditClient.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnEditClient.setForeground(new java.awt.Color(255, 255, 255));
        btnEditClient.setText("Editar");
        btnEditClient.setBorder(null);
        btnEditClient.setBorderPainted(false);
        btnEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClientActionPerformed(evt);
            }
        });

        btnNewClient.setBackground(new java.awt.Color(0, 153, 51));
        btnNewClient.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnNewClient.setForeground(new java.awt.Color(255, 255, 255));
        btnNewClient.setText("Nuevo Cliente");
        btnNewClient.setBorder(null);
        btnNewClient.setBorderPainted(false);
        btnNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleToMove1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleToMove2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTitleToMove3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtFirstNameClient)
                    .addComponent(lblTitleToMove5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLastNameClient)
                    .addComponent(lblTitleToMove6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumberPhoneClient)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleToMove1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleToMove3)
                    .addComponent(lblIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleToMove2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFirstNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitleToMove5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitleToMove6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumberPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClients);

        btnRefresh.setBackground(new java.awt.Color(0, 0, 204));
        btnRefresh.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refrescar Datos");
        btnRefresh.setBorder(null);
        btnRefresh.setBorderPainted(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTitleToMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitleToMoveMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblTitleToMoveMousePressed

    private void lblTitleToMoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitleToMoveMouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_lblTitleToMoveMouseDragged

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cleanFields();
        blockFields();
        buttonsByDefault();
        showListClients();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        cleanFields();
        blockFields();
        buttonsByDefault();
        showListClients();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewClientActionPerformed
        V_addClient win = new V_addClient(new javax.swing.JDialog(), true);
        win.setVisible(true);
    }//GEN-LAST:event_btnNewClientActionPerformed

    private void btnEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClientActionPerformed
        if (btnEditClient.getText().equals("Editar")) {
            btnEditClient.setText("Guardar Cambios");
            btnDeleteClient.setEnabled(false);
            unblockFields();

        } else if (btnEditClient.getText().equals("Guardar Cambios")) {
            if (txtFirstNameClient.getText().equals("") || txtLastNameClient.getText().equals("") || txtNumberPhoneClient.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe asegurarse de rellenar todos los campos!");
            } else {
                if (txtNumberPhoneClient.getText().length() < 8) {
                    JOptionPane.showMessageDialog(null, "El número de telefono debe contener 8 dígitos!");
                } else {
                    btnEditClient.setText("Editar");
                    client.setIdClient(Integer.parseInt(lblIdClient.getText()));
                    client.setFirstName(txtFirstNameClient.getText());
                    client.setLastName(txtLastNameClient.getText());
                    client.setNumberphone(txtNumberPhoneClient.getText());

                    business.B_updateClient(client);

                    cleanFields();
                    blockFields();
                    buttonsByDefault();
                    showListClients();
                }
            }
        }
    }//GEN-LAST:event_btnEditClientActionPerformed

    private void btnDeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClientActionPerformed
        client = new E_clients();
        client.setIdClient(Integer.parseInt(lblIdClient.getText()));

        if (business.B_deleteClient(client) == false) {
            JOptionPane.showMessageDialog(null, "No puede eliminar un cliente con registros de compras!");
        }

        cleanFields();
        blockFields();
        buttonsByDefault();
        showListClients();

    }//GEN-LAST:event_btnDeleteClientActionPerformed

    private void tbClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientsMouseClicked
        int selectedRow = tbClients.rowAtPoint(evt.getPoint());

        btnNewClient.setEnabled(false);
        btnEditClient.setEnabled(true);
        btnDeleteClient.setEnabled(true);
        btnCancel.setEnabled(true);

        lblIdClient.setText(tbClients.getValueAt(selectedRow, 0).toString());
        txtFirstNameClient.setText(tbClients.getValueAt(selectedRow, 1).toString());
        txtLastNameClient.setText(tbClients.getValueAt(selectedRow, 2).toString());
        txtNumberPhoneClient.setText(tbClients.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_tbClientsMouseClicked

    private void txtNumberPhoneClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumberPhoneClientKeyTyped
        char caracter = evt.getKeyChar();

        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b') && (caracter != '\n')) {
            evt.consume();
            System.out.println("NOO!");
        }

        if (txtNumberPhoneClient.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumberPhoneClientKeyTyped

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(V_clientCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(V_clientCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(V_clientCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(V_clientCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                V_clientCrud dialog = new V_clientCrud(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteClient;
    private javax.swing.JButton btnEditClient;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewClient;
    public static javax.swing.JButton btnRefresh;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdClient;
    private javax.swing.JLabel lblTitleToMove;
    private javax.swing.JLabel lblTitleToMove1;
    private javax.swing.JLabel lblTitleToMove2;
    private javax.swing.JLabel lblTitleToMove3;
    private javax.swing.JLabel lblTitleToMove5;
    private javax.swing.JLabel lblTitleToMove6;
    private javax.swing.JTable tbClients;
    private javax.swing.JTextField txtFirstNameClient;
    private javax.swing.JTextField txtLastNameClient;
    private javax.swing.JTextField txtNumberPhoneClient;
    // End of variables declaration//GEN-END:variables
}
