/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.MouseInfo;
import java.awt.Point;

/**
 *
 * @author LilJade
 */
public class V_productsCrud extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form V_productsCrud
     */
    public V_productsCrud() {
        initComponents();
        this.setLocationRelativeTo(null);
        blockFields();
        buttonsByDefault();
    }
    
    //put the default state for all buttons
    void buttonsByDefault() {
        btnChangeImg.setEnabled(false);
        btnEditPriceSale.setEnabled(false);
        btnEditStock.setEnabled(false);

        btnNewProd.setEnabled(true);
        btnEditProd.setEnabled(false);
        btnDeleteProd.setEnabled(false);
        
        btnSaveAll.setEnabled(false);
        btnCancelAll.setEnabled(false);
    }
    
    //clean all fields of the form
    void cleanFields() {
        lblImgProd.setIcon(null);
        lblId.setText("");
        txtNameProd.setText("");
        txtPriceInit_U.setText("");
        txtPriceSale_U.setText("");
        txtQuantityPP.setText("");
        txtPriceInit_P.setText("");
        txtPriceSale_P.setText("");
    }
    
    //block all fields of the form
    void blockFields() {
        txtNameProd.setEditable(false);
        txtPriceInit_U.setEditable(false);
        txtPriceSale_U.setEditable(false);
        txtPriceInit_P.setEditable(false);
        txtPriceSale_P.setEditable(false);
        cmbCategoryProd.setEnabled(false);
    }
    
    //unblock all fields of the form
    void unblockFields() {
        txtNameProd.setEditable(true);
        txtPriceInit_U.setEditable(true);
        txtPriceSale_U.setEditable(true);
        txtPriceInit_P.setEditable(true);
        txtPriceSale_P.setEditable(true);
        cmbCategoryProd.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducts = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbCategoryProds = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtSearchProd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblImgProd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPriceInit_U = new javax.swing.JTextField();
        txtPriceInit_P = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPriceSale_U = new javax.swing.JTextField();
        txtPriceSale_P = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbCategoryProd = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnEditPriceSale = new javax.swing.JButton();
        btnChangeImg = new javax.swing.JButton();
        txtStockU = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnEditStock = new javax.swing.JButton();
        btnSaveAll = new javax.swing.JButton();
        btnCancelAll = new javax.swing.JButton();
        btnEditProd = new javax.swing.JButton();
        btnDeleteProd = new javax.swing.JButton();
        btnNewProd = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtQuantityPP = new javax.swing.JTextField();
        txtStockP = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        btnRefresh1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTable.setBackground(new java.awt.Color(204, 255, 255));
        pnTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Precio Venta", "Existencias"
            }
        ));
        tbProducts.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tbProducts);
        if (tbProducts.getColumnModel().getColumnCount() > 0) {
            tbProducts.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbProducts.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbProducts.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbProducts.getColumnModel().getColumn(3).setPreferredWidth(95);
        }

        jLabel2.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel2.setText("Ver productos por categoría: ");

        cmbCategoryProds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel13.setText("Buscar un producto: ");

        txtSearchProd.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnTableLayout = new javax.swing.GroupLayout(pnTable);
        pnTable.setLayout(pnTableLayout);
        pnTableLayout.setHorizontalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(pnTableLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCategoryProds, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnTableLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchProd)))
                .addContainerGap())
        );
        pnTableLayout.setVerticalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCategoryProds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSearchProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 660));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgProd.setIcon(new javax.swing.ImageIcon("F:\\NetBeansProjects\\wStore\\src\\main\\java\\imgs\\paquete.png")); // NOI18N
        lblImgProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImgProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 36, 197, 110));

        jLabel3.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 157, 360, -1));

        txtNameProd.setEditable(false);
        txtNameProd.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N
        jPanel1.add(txtNameProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 181, 360, -1));

        jLabel4.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel4.setText("Precio Inicial por Unidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 292, -1, -1));

        jLabel5.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel5.setText("Precio Inicial por Paquete");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        txtPriceInit_U.setEditable(false);
        txtPriceInit_U.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N
        jPanel1.add(txtPriceInit_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 166, -1));

        txtPriceInit_P.setEditable(false);
        txtPriceInit_P.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N
        jPanel1.add(txtPriceInit_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 174, -1));

        jLabel6.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel6.setText("Precio Venta por Unidad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        txtPriceSale_U.setEditable(false);
        txtPriceSale_U.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N
        jPanel1.add(txtPriceSale_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 167, -1));

        txtPriceSale_P.setEditable(false);
        txtPriceSale_P.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N
        jPanel1.add(txtPriceSale_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 175, -1));

        jLabel7.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel7.setText("Precio Venta por Paquete");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        cmbCategoryProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbCategoryProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 209, 279, -1));

        jLabel8.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel8.setText("Categoría:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 209, -1, -1));

        btnEditPriceSale.setBackground(new java.awt.Color(153, 204, 255));
        btnEditPriceSale.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnEditPriceSale.setText("Editar Precio de Venta");
        btnEditPriceSale.setBorder(null);
        btnEditPriceSale.setBorderPainted(false);
        btnEditPriceSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditPriceSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPriceSaleActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditPriceSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 390, 200, 26));

        btnChangeImg.setBackground(new java.awt.Color(102, 51, 255));
        btnChangeImg.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnChangeImg.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeImg.setText("Cambiar Imagen");
        btnChangeImg.setBorder(null);
        btnChangeImg.setBorderPainted(false);
        btnChangeImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeImgActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangeImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 106, 140, 40));

        txtStockU.setEditable(false);
        txtStockU.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N
        jPanel1.add(txtStockU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 273, -1));

        jLabel10.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel10.setText("Existencias:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        btnEditStock.setBackground(new java.awt.Color(153, 204, 255));
        btnEditStock.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnEditStock.setText("Gestionar Existencias");
        btnEditStock.setBorder(null);
        btnEditStock.setBorderPainted(false);
        btnEditStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStockActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 195, 26));

        btnSaveAll.setBackground(new java.awt.Color(0, 153, 51));
        btnSaveAll.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnSaveAll.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveAll.setText("Guardar Cambios");
        btnSaveAll.setBorder(null);
        btnSaveAll.setBorderPainted(false);
        btnSaveAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 597, 177, 36));

        btnCancelAll.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelAll.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnCancelAll.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelAll.setText("Cancelar");
        btnCancelAll.setBorder(null);
        btnCancelAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 597, 177, 36));

        btnEditProd.setBackground(new java.awt.Color(255, 204, 51));
        btnEditProd.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnEditProd.setText("Editar");
        btnEditProd.setBorder(null);
        btnEditProd.setBorderPainted(false);
        btnEditProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 560, 175, 26));

        btnDeleteProd.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteProd.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnDeleteProd.setText("Eliminar");
        btnDeleteProd.setBorder(null);
        btnDeleteProd.setBorderPainted(false);
        btnDeleteProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnDeleteProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 560, 179, 26));

        btnNewProd.setBackground(new java.awt.Color(102, 204, 0));
        btnNewProd.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnNewProd.setText("Nuevo Producto");
        btnNewProd.setBorder(null);
        btnNewProd.setBorderPainted(false);
        btnNewProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 523, 360, 31));

        jLabel11.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel11.setText("ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 12, -1, -1));

        lblId.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("11111001111");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 12, 145, -1));

        jLabel12.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel12.setText("Cantidad por Paquete:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 174, -1));

        txtQuantityPP.setEditable(false);
        txtQuantityPP.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N
        jPanel1.add(txtQuantityPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 174, -1));

        txtStockP.setEditable(false);
        txtStockP.setFont(new java.awt.Font("MADE TOMMY", 1, 12)); // NOI18N
        jPanel1.add(txtStockP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 273, -1));

        btnRefresh.setBackground(new java.awt.Color(0, 51, 204));
        btnRefresh.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refrescar Datos");
        btnRefresh.setBorder(null);
        btnRefresh.setBorderPainted(false);
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 140, 40));

        jLabel9.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel9.setText("Imagen del producto:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 380, 660));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTittle.setFont(new java.awt.Font("MADE TOMMY", 1, 30)); // NOI18N
        lblTittle.setText("Configurar Productos");
        lblTittle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblTittleMouseDragged(evt);
            }
        });
        lblTittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTittleMousePressed(evt);
            }
        });

        btnRefresh1.setBackground(new java.awt.Color(204, 0, 0));
        btnRefresh1.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setText("Cerrar");
        btnRefresh1.setBorder(null);
        btnRefresh1.setBorderPainted(false);
        btnRefresh1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTittle, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTittle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefresh1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditPriceSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPriceSaleActionPerformed
        V_pricesProductsConfig win = new V_pricesProductsConfig(this, true);
        win.setVisible(true);
    }//GEN-LAST:event_btnEditPriceSaleActionPerformed

    private void btnChangeImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeImgActionPerformed

    private void btnEditStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStockActionPerformed
        V_stockProdConfig winStockConfig = new V_stockProdConfig(this, true);
        winStockConfig.setVisible(true);
    }//GEN-LAST:event_btnEditStockActionPerformed

    private void btnSaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveAllActionPerformed

    //cancell all operations
    private void btnCancelAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAllActionPerformed
        cleanFields();
        blockFields();
        buttonsByDefault();
    }//GEN-LAST:event_btnCancelAllActionPerformed

    private void btnEditProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditProdActionPerformed

    private void btnNewProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProdActionPerformed
        cleanFields();
        unblockFields();
        
        btnChangeImg.setEnabled(true);
        btnEditPriceSale.setEnabled(true);
        btnEditStock.setEnabled(true);

        btnNewProd.setEnabled(false);
        btnEditProd.setEnabled(false);
        btnDeleteProd.setEnabled(false);
        
        btnSaveAll.setEnabled(true);
        btnCancelAll.setEnabled(true);
    }//GEN-LAST:event_btnNewProdActionPerformed

    //refresh components of the form
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        cleanFields();
        blockFields();
        buttonsByDefault();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    //to move form
    private void lblTittleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTittleMouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_lblTittleMouseDragged

    //to move form
    private void lblTittleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTittleMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblTittleMousePressed

    /*  MAIN METHOD  */
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(V_productsCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(V_productsCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(V_productsCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(V_productsCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new V_productsCrud().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelAll;
    private javax.swing.JButton btnChangeImg;
    private javax.swing.JButton btnDeleteProd;
    private javax.swing.JButton btnEditPriceSale;
    private javax.swing.JButton btnEditProd;
    private javax.swing.JButton btnEditStock;
    private javax.swing.JButton btnNewProd;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnSaveAll;
    private javax.swing.JComboBox<String> cmbCategoryProd;
    private javax.swing.JComboBox<String> cmbCategoryProds;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImgProd;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel pnTable;
    private javax.swing.JTable tbProducts;
    private javax.swing.JTextField txtNameProd;
    private javax.swing.JTextField txtPriceInit_P;
    private javax.swing.JTextField txtPriceInit_U;
    private javax.swing.JTextField txtPriceSale_P;
    private javax.swing.JTextField txtPriceSale_U;
    private javax.swing.JTextField txtQuantityPP;
    private javax.swing.JTextField txtSearchProd;
    private javax.swing.JTextField txtStockP;
    private javax.swing.JTextField txtStockU;
    // End of variables declaration//GEN-END:variables
}
