/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author LilJade
 */
public class V_Sale extends javax.swing.JFrame {

    /**
     * Creates new form V_Sale
     */
    public V_Sale() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        blockButtons();
        cleanFields();
        blockFields();
    }
    
    void cleanFields() {
        lblSelectedProd.setText("");
        txtQuantityU.setText("");
        txtQuantityP.setText("");
        lblStock.setText("");
        lblIdProd.setText("");
        lblArtSale.setText("");
        txtTotal.setText("");
        
        txtSearchClient.setText("");
    }
    
    void blockFields() {
        txtQuantityU.setEnabled(false);
        txtQuantityP.setEnabled(false);
        tbDetailSale.setEnabled(false);
        txtTotal.setEnabled(false);
        
        txtSearchClient.setEnabled(false);
        tbClient.setEnabled(false);
        
        ckbAddClient.setEnabled(false);
    }
    
    void unblockFields() {
        txtQuantityU.setEnabled(true);
        txtQuantityP.setEnabled(true);
        tbDetailSale.setEnabled(true);
        txtTotal.setEnabled(true);
        
        ckbAddClient.setEnabled(true);
    }
    
    void blockButtons() {
        btnSearchProd.setEnabled(false);
        btnAddProduct.setEnabled(false);
        btnCancelAddProd.setEnabled(false);
        btnDeleteProd.setEnabled(false);
        
        btnSelectClient.setEnabled(false);
        btnAddClient.setEnabled(false);
        
        btnCompleteSale.setEnabled(false);
        btnPrint.setEnabled(false);
        btnCancelSale.setEnabled(false);
    }
    
    void unblockButtons() {
        btnSearchProd.setEnabled(true);
        btnAddProduct.setEnabled(true);
        btnCancelAddProd.setEnabled(true);
        btnDeleteProd.setEnabled(true);
        
        btnCompleteSale.setEnabled(true);
        btnPrint.setEnabled(true);
        btnCancelSale.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfigSale = new javax.swing.JPanel();
        lblIdSale = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        pnlCliente = new javax.swing.JPanel();
        txtSearchClient = new javax.swing.JTextField();
        btnAddClient = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbClient = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        btnSelectClient = new javax.swing.JButton();
        ckbAddClient = new javax.swing.JCheckBox();
        btnNewSale = new javax.swing.JButton();
        btnCompleteSale = new javax.swing.JButton();
        btnCancelSale = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        pnlProdsAdd = new javax.swing.JPanel();
        lblLogoWStore = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearchProd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtQuantityU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblIdProd = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSelectedProd = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCancelAddProd = new javax.swing.JButton();
        lblStock = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtQuantityP = new javax.swing.JTextField();
        pnlOptions = new javax.swing.JPanel();
        btnProduct = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        pnlTableSale = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDetailSale = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnDeleteProd = new javax.swing.JButton();
        lblArtSale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlConfigSale.setBackground(new java.awt.Color(204, 204, 255));
        pnlConfigSale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIdSale.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblIdSale.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdSale.setText("11111001111");
        lblIdSale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel12.setText("ID:");

        jLabel14.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel14.setText("Fecha:");

        lblDate.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("31 / 12 / 9999");
        lblDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSearchClient.setFont(new java.awt.Font("MADE TOMMY", 0, 14)); // NOI18N

        btnAddClient.setFont(new java.awt.Font("MADE TOMMY", 0, 18)); // NOI18N
        btnAddClient.setText("Registrar nuevo cliente");
        btnAddClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddClient.setContentAreaFilled(false);
        btnAddClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });

        tbClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tbClient.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tbClient);
        if (tbClient.getColumnModel().getColumnCount() > 0) {
            tbClient.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbClient.getColumnModel().getColumn(1).setPreferredWidth(195);
        }

        jLabel16.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel16.setText("Buscar Cliente:");

        btnSelectClient.setFont(new java.awt.Font("MADE TOMMY", 0, 18)); // NOI18N
        btnSelectClient.setText("Seleccionar");
        btnSelectClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSelectClient.setContentAreaFilled(false);
        btnSelectClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchClient)
                    .addComponent(btnAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSelectClient, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelectClient)
                .addGap(29, 29, 29)
                .addComponent(btnAddClient)
                .addContainerGap())
        );

        ckbAddClient.setText("Especificar cliente");
        ckbAddClient.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbAddClientItemStateChanged(evt);
            }
        });
        ckbAddClient.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbAddClientStateChanged(evt);
            }
        });
        ckbAddClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbAddClientMouseClicked(evt);
            }
        });
        ckbAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbAddClientActionPerformed(evt);
            }
        });

        btnNewSale.setBackground(new java.awt.Color(0, 153, 51));
        btnNewSale.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        btnNewSale.setForeground(new java.awt.Color(255, 255, 255));
        btnNewSale.setText("Nueva Venta");
        btnNewSale.setBorder(null);
        btnNewSale.setBorderPainted(false);
        btnNewSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSaleActionPerformed(evt);
            }
        });

        btnCompleteSale.setBackground(new java.awt.Color(0, 153, 51));
        btnCompleteSale.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        btnCompleteSale.setForeground(new java.awt.Color(255, 255, 255));
        btnCompleteSale.setText("Realizar Venta");
        btnCompleteSale.setBorder(null);
        btnCompleteSale.setBorderPainted(false);
        btnCompleteSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteSaleActionPerformed(evt);
            }
        });

        btnCancelSale.setBackground(new java.awt.Color(204, 0, 51));
        btnCancelSale.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        btnCancelSale.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelSale.setText("Cancelar Venta");
        btnCancelSale.setBorder(null);
        btnCancelSale.setBorderPainted(false);
        btnCancelSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSaleActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(51, 0, 255));
        btnPrint.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Imprimir Factura");
        btnPrint.setBorder(null);
        btnPrint.setBorderPainted(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConfigSaleLayout = new javax.swing.GroupLayout(pnlConfigSale);
        pnlConfigSale.setLayout(pnlConfigSaleLayout);
        pnlConfigSaleLayout.setHorizontalGroup(
            pnlConfigSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConfigSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlConfigSaleLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(lblIdSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfigSaleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCompleteSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewSale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbAddClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlConfigSaleLayout.setVerticalGroup(
            pnlConfigSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConfigSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSale, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfigSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbAddClient)
                .addGap(80, 80, 80)
                .addComponent(btnCompleteSale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelSale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewSale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlProdsAdd.setBackground(new java.awt.Color(255, 204, 102));
        pnlProdsAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLogoWStore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoWStore.setIcon(new javax.swing.ImageIcon("F:\\NetBeansProjects\\wStore\\src\\main\\java\\imgs\\bolsaCompra.png")); // NOI18N
        lblLogoWStore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel2.setText("Seleccionar producto: ");

        btnSearchProd.setBackground(new java.awt.Color(51, 51, 255));
        btnSearchProd.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        btnSearchProd.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchProd.setText("Buscar Producto");
        btnSearchProd.setBorder(null);
        btnSearchProd.setBorderPainted(false);
        btnSearchProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel3.setText("Producto Seleccionado:");

        txtQuantityU.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        txtQuantityU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityUActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad:");

        lblIdProd.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblIdProd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdProd.setText("11111001111");
        lblIdProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel6.setText("Id del producto:");

        lblSelectedProd.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        lblSelectedProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedProd.setText(" ");
        lblSelectedProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAddProduct.setBackground(new java.awt.Color(0, 153, 51));
        btnAddProduct.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Agregar Producto");
        btnAddProduct.setBorder(null);
        btnAddProduct.setBorderPainted(false);

        jLabel10.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel10.setText("Stock:");

        btnCancelAddProd.setBackground(new java.awt.Color(204, 0, 51));
        btnCancelAddProd.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        btnCancelAddProd.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelAddProd.setText("Cancelar");
        btnCancelAddProd.setBorder(null);
        btnCancelAddProd.setBorderPainted(false);

        lblStock.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStock.setText("11111001111");
        lblStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel17.setText("Vender por paquete:");

        txtQuantityP.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        txtQuantityP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProdsAddLayout = new javax.swing.GroupLayout(pnlProdsAdd);
        pnlProdsAdd.setLayout(pnlProdsAddLayout);
        pnlProdsAddLayout.setHorizontalGroup(
            pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdsAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoWStore, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlProdsAddLayout.createSequentialGroup()
                        .addComponent(txtQuantityU, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdsAddLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblSelectedProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProdsAddLayout.createSequentialGroup()
                        .addComponent(txtQuantityP, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlProdsAddLayout.setVerticalGroup(
            pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdsAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProdsAddLayout.createSequentialGroup()
                        .addGroup(pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearchProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblSelectedProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantityU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lblIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProdsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btnCancelAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel17)
                            .addComponent(txtQuantityP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblLogoWStore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlOptions.setBackground(new java.awt.Color(255, 255, 255));
        pnlOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProduct.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnProduct.setText("Inventario");
        btnProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProduct.setContentAreaFilled(false);
        btnProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        pnlOptions.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 200, 20));

        btnCategory.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        btnCategory.setText("Config Categorías");
        btnCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCategory.setContentAreaFilled(false);
        btnCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        pnlOptions.add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));

        pnlTableSale.setBackground(new java.awt.Color(153, 204, 255));
        pnlTableSale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTotal.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText("11111001111");

        jLabel1.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel1.setText("Total: $");

        tbDetailSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDetailSale);

        jLabel8.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        jLabel8.setText("Artículos Vendidos:");

        btnDeleteProd.setBackground(new java.awt.Color(204, 0, 51));
        btnDeleteProd.setFont(new java.awt.Font("MADE TOMMY", 1, 18)); // NOI18N
        btnDeleteProd.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteProd.setText("Eliminar Producto");
        btnDeleteProd.setBorder(null);
        btnDeleteProd.setBorderPainted(false);
        btnDeleteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProdActionPerformed(evt);
            }
        });

        lblArtSale.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblArtSale.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblArtSale.setText("11111001111");
        lblArtSale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlTableSaleLayout = new javax.swing.GroupLayout(pnlTableSale);
        pnlTableSale.setLayout(pnlTableSaleLayout);
        pnlTableSaleLayout.setHorizontalGroup(
            pnlTableSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlTableSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteProd, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblArtSale, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTableSaleLayout.setVerticalGroup(
            pnlTableSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableSaleLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTableSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel8)
                        .addComponent(lblArtSale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeleteProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTableSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProdsAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConfigSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlProdsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTableSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlConfigSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantityUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityUActionPerformed

    private void btnDeleteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteProdActionPerformed

    private void btnNewSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSaleActionPerformed
        unblockFields();
        unblockButtons();
        btnNewSale.setEnabled(false);
    }//GEN-LAST:event_btnNewSaleActionPerformed

    private void btnCompleteSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompleteSaleActionPerformed

    private void btnCancelSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSaleActionPerformed
        cleanFields();
        blockFields();
        blockButtons();
        btnNewSale.setEnabled(true);
    }//GEN-LAST:event_btnCancelSaleActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void ckbAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbAddClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbAddClientActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        V_productsCrud win = new V_productsCrud();
        
        win.setVisible(true);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        V_categoryCrud win = new V_categoryCrud();
        
        win.setVisible(true);
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void ckbAddClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbAddClientMouseClicked
        if (ckbAddClient.isSelected()) {
            txtSearchClient.setEnabled(true);
            tbClient.setEnabled(true);
            
            btnSelectClient.setEnabled(true);
            btnAddClient.setEnabled(true);
        
            pnlCliente.setEnabled(true);
        } else {
            txtSearchClient.setEnabled(true);
            tbClient.setEnabled(true);
        
            btnSelectClient.setEnabled(true);
            btnAddClient.setEnabled(true);
            
            pnlCliente.setEnabled(true);
        }
    }//GEN-LAST:event_ckbAddClientMouseClicked

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        V_addClient win = new V_addClient(this, true);
        win.setVisible(true);
    }//GEN-LAST:event_btnAddClientActionPerformed

    private void txtQuantityPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityPActionPerformed

    private void ckbAddClientStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbAddClientStateChanged

    }//GEN-LAST:event_ckbAddClientStateChanged

    private void ckbAddClientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbAddClientItemStateChanged
        
    }//GEN-LAST:event_ckbAddClientItemStateChanged

    private void btnSearchProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProdActionPerformed
        V_SearchProduct win = new V_SearchProduct(this, true);
        win.setVisible(true);
    }//GEN-LAST:event_btnSearchProdActionPerformed

    /*  MAIN METHOD  */
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(V_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(V_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(V_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(V_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new V_Sale().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancelAddProd;
    private javax.swing.JButton btnCancelSale;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnCompleteSale;
    private javax.swing.JButton btnDeleteProd;
    private javax.swing.JButton btnNewSale;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnSearchProd;
    private javax.swing.JButton btnSelectClient;
    private javax.swing.JCheckBox ckbAddClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArtSale;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblIdProd;
    private javax.swing.JLabel lblIdSale;
    private javax.swing.JLabel lblLogoWStore;
    private javax.swing.JLabel lblSelectedProd;
    private javax.swing.JLabel lblStock;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlConfigSale;
    private javax.swing.JPanel pnlOptions;
    private javax.swing.JPanel pnlProdsAdd;
    private javax.swing.JPanel pnlTableSale;
    private javax.swing.JTable tbClient;
    private javax.swing.JTable tbDetailSale;
    private javax.swing.JTextField txtQuantityP;
    private javax.swing.JTextField txtQuantityU;
    private javax.swing.JTextField txtSearchClient;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
