package views;

import entities.E_users;
import business.B_users;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LilJade
 */
public class V_userCrud extends javax.swing.JDialog {

    int x, y;
    B_users business = new B_users();
    E_users user = new E_users();

    // Creates new form V_userCrud
    public V_userCrud(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cleanFields();
        blockFields();
        buttonsByDefault();

        showListUsers();
    }

    void showListUsers() {
        String titles[] = {"Id", "Nombres", "Apellidos", "Correo", "Password"};

        DefaultTableModel df = new DefaultTableModel(null, titles);

        ArrayList<E_users> list = business.B_listUsers();
        Iterator i = list.iterator();
        String rows[] = new String[5];

        while (i.hasNext()) {
            E_users user;
            user = (E_users) i.next();

            rows[0] = String.valueOf(user.getIdUser());
            rows[1] = user.getFirstName();
            rows[2] = user.getLastName();
            rows[3] = user.getEmail();
            rows[4] = user.getPass();

            df.addRow(rows);
        }

        tbUsers.setModel(df);

        tbUsers.getColumnModel().getColumn(0).setMaxWidth(25);
        tbUsers.getColumnModel().getColumn(0).setMinWidth(25);
        tbUsers.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(25);
        tbUsers.getTableHeader().getColumnModel().getColumn(0).setMinWidth(25);

        tbUsers.getColumnModel().getColumn(4).setMaxWidth(0);
        tbUsers.getColumnModel().getColumn(4).setMinWidth(0);
        tbUsers.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(0);
        tbUsers.getTableHeader().getColumnModel().getColumn(4).setMinWidth(0);
    }

    void cleanFields() {
        lblIdUser.setText("");
        txtFirstNameUser.setText("");
        txtLastNameUser.setText("");
        txtEmailUser.setText("");
        txtPassUser.setText("");
        txtRepeatPassUser.setText("");
    }

    void blockFields() {
        txtFirstNameUser.setEnabled(false);
        txtLastNameUser.setEnabled(false);
        txtEmailUser.setEnabled(false);
        txtPassUser.setEnabled(false);
        txtRepeatPassUser.setEnabled(false);
    }

    void unblockFields() {
        txtFirstNameUser.setEnabled(true);
        txtLastNameUser.setEnabled(true);
        txtEmailUser.setEnabled(true);
        txtPassUser.setEnabled(true);
        txtRepeatPassUser.setEnabled(true);
    }

    void buttonsByDefault() {
        btnNewUser.setEnabled(true);
        btnNewUser.setText("Nuevo Usuario");
        btnEditUser.setEnabled(false);
        btnEditUser.setText("Editar");
        btnDeleteUser.setEnabled(false);
        btnCancel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        lblTitleToMove = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTitleToMove1 = new javax.swing.JLabel();
        lblTitleToMove2 = new javax.swing.JLabel();
        lblTitleToMove3 = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        txtFirstNameUser = new javax.swing.JTextField();
        txtLastNameUser = new javax.swing.JTextField();
        lblTitleToMove5 = new javax.swing.JLabel();
        txtEmailUser = new javax.swing.JTextField();
        lblTitleToMove6 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnNewUser = new javax.swing.JButton();
        lblTitleToMove7 = new javax.swing.JLabel();
        txtPassUser = new javax.swing.JPasswordField();
        txtRepeatPassUser = new javax.swing.JPasswordField();
        lblTitleToMove8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        scplTableUsers = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(204, 0, 0));
        btnExit.setFont(new java.awt.Font("MADE TOMMY", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 90, 50));

        lblTitleToMove.setFont(new java.awt.Font("MADE TOMMY", 1, 36)); // NOI18N
        lblTitleToMove.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove.setText("Lista de Usuarios");
        lblTitleToMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblTitleToMoveMouseDragged(evt);
            }
        });
        lblTitleToMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTitleToMoveMousePressed(evt);
            }
        });
        jPanel2.add(lblTitleToMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 710, 67));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitleToMove1.setFont(new java.awt.Font("MADE TOMMY", 1, 24)); // NOI18N
        lblTitleToMove1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleToMove1.setText("Configuración");

        lblTitleToMove2.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove2.setText("Nombres:");

        lblTitleToMove3.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove3.setText("ID: ");

        lblIdUser.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblIdUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdUser.setText("11111001111");
        lblIdUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFirstNameUser.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        txtFirstNameUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameUserKeyReleased(evt);
            }
        });

        txtLastNameUser.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        txtLastNameUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameUserKeyReleased(evt);
            }
        });

        lblTitleToMove5.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove5.setText("Apellidos:");

        txtEmailUser.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        txtEmailUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailUserKeyReleased(evt);
            }
        });

        lblTitleToMove6.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove6.setText("Correo: ");

        btnCancel.setBackground(new java.awt.Color(204, 0, 0));
        btnCancel.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDeleteUser.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteUser.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnDeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setText("Borrar");
        btnDeleteUser.setBorder(null);
        btnDeleteUser.setBorderPainted(false);
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnEditUser.setBackground(new java.awt.Color(255, 153, 0));
        btnEditUser.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnEditUser.setForeground(new java.awt.Color(255, 255, 255));
        btnEditUser.setText("Editar");
        btnEditUser.setBorder(null);
        btnEditUser.setBorderPainted(false);
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnNewUser.setBackground(new java.awt.Color(0, 153, 51));
        btnNewUser.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnNewUser.setText("Nuevo Usuario");
        btnNewUser.setBorder(null);
        btnNewUser.setBorderPainted(false);
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });

        lblTitleToMove7.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove7.setText("Contraseña:");

        txtPassUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassUserKeyReleased(evt);
            }
        });

        txtRepeatPassUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRepeatPassUserKeyReleased(evt);
            }
        });

        lblTitleToMove8.setFont(new java.awt.Font("MADE TOMMY", 1, 14)); // NOI18N
        lblTitleToMove8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleToMove8.setText("Repetir contraseña:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleToMove1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleToMove2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTitleToMove3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtFirstNameUser)
                    .addComponent(lblTitleToMove5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLastNameUser)
                    .addComponent(lblTitleToMove6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmailUser)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleToMove7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassUser)
                    .addComponent(lblTitleToMove8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRepeatPassUser))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleToMove1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleToMove3)
                    .addComponent(lblIdUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleToMove2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitleToMove5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitleToMove6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitleToMove7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitleToMove8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRepeatPassUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "I", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUsers.setShowGrid(true);
        tbUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsersMouseClicked(evt);
            }
        });
        scplTableUsers.setViewportView(tbUsers);

        btnRefresh.setBackground(new java.awt.Color(0, 0, 204));
        btnRefresh.setFont(new java.awt.Font("MADE TOMMY", 1, 20)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refrescar Datos");
        btnRefresh.setBorder(null);
        btnRefresh.setBorderPainted(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scplTableUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scplTableUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void lblTitleToMoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitleToMoveMouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_lblTitleToMoveMouseDragged

    private void lblTitleToMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitleToMoveMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblTitleToMoveMousePressed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cleanFields();
        blockFields();
        buttonsByDefault();
        showListUsers();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        String valueButton = btnNewUser.getText();

        System.out.println(valueButton);

        switch (valueButton) {
            case "Nuevo Usuario":

                cleanFields();
                unblockFields();

                btnNewUser.setEnabled(true);
                btnNewUser.setText("Agregar");
                btnCancel.setEnabled(true);

                System.out.println("Por agregar");

                break;

            case "Agregar":
                if (txtFirstNameUser.getText().equals("") || txtLastNameUser.getText().equals("")
                        || txtEmailUser.getText().equals("") || txtPassUser.getText().equals("")
                        || txtRepeatPassUser.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios!");
                } else {
                    if (!txtPassUser.getText().equals(txtRepeatPassUser.getText())) {
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden!");
                    } else {
                        user.setFirstName(txtFirstNameUser.getText());
                        user.setLastName(txtLastNameUser.getText());
                        user.setEmail(txtEmailUser.getText());
                        user.setPass(txtPassUser.getText());
                        business.B_insertUser(user);
                        btnNewUser.setText("Nuevo Usuario");

                        cleanFields();
                        blockFields();
                        buttonsByDefault();
                        System.out.println("Agregando");
                    }
                }

                break;
        }

        showListUsers();
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        cleanFields();
        blockFields();
        buttonsByDefault();
        showListUsers();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tbUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsersMouseClicked
        int seleccionar = tbUsers.rowAtPoint(evt.getPoint());

        lblIdUser.setText(String.valueOf(tbUsers.getValueAt(seleccionar, 0)));
        txtFirstNameUser.setText(String.valueOf(tbUsers.getValueAt(seleccionar, 1)));
        txtLastNameUser.setText(String.valueOf(tbUsers.getValueAt(seleccionar, 2)));
        txtEmailUser.setText(String.valueOf(tbUsers.getValueAt(seleccionar, 3)));
        txtPassUser.setText(String.valueOf(tbUsers.getValueAt(seleccionar, 4)));
        txtRepeatPassUser.setText(String.valueOf(tbUsers.getValueAt(seleccionar, 4)));

        btnNewUser.setEnabled(false);
        btnEditUser.setEnabled(true);
        btnDeleteUser.setEnabled(true);
        btnCancel.setEnabled(true);
    }//GEN-LAST:event_tbUsersMouseClicked

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        String buttonValue = btnEditUser.getText();

        switch (buttonValue) {
            case "Editar":
                btnEditUser.setText("Guardar Cambios");
                btnNewUser.setEnabled(false);
                btnDeleteUser.setEnabled(false);
                btnCancel.setEnabled(true);
                unblockFields();
                break;

            case "Guardar Cambios":
                if (txtFirstNameUser.getText().equals("") || txtLastNameUser.getText().equals("")
                        || txtEmailUser.getText().equals("") || txtPassUser.getText().equals("")
                        || txtRepeatPassUser.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios!");
                } else {
                    if (!txtPassUser.getText().equals(txtRepeatPassUser.getText())) {
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden!");
                    } else {
                        user.setIdUser(Integer.parseInt(lblIdUser.getText()));
                        user.setFirstName(txtFirstNameUser.getText());
                        user.setLastName(txtLastNameUser.getText());
                        user.setEmail(txtEmailUser.getText());
                        user.setPass(txtPassUser.getText());

                        business.B_updateUser(user);

                        btnEditUser.setText("Editar");
                        cleanFields();
                        blockFields();
                        buttonsByDefault();
                        showListUsers();
                    }
                }
                break;
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        user.setIdUser(Integer.parseInt(lblIdUser.getText()));

        business.B_deleteUser(user);

        cleanFields();
        blockFields();
        buttonsByDefault();
        showListUsers();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void txtFirstNameUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameUserKeyReleased
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            txtLastNameUser.requestFocus();
        }
    }//GEN-LAST:event_txtFirstNameUserKeyReleased

    private void txtLastNameUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameUserKeyReleased
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            txtEmailUser.requestFocus();
        }
    }//GEN-LAST:event_txtLastNameUserKeyReleased

    private void txtEmailUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailUserKeyReleased
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            txtPassUser.requestFocus();
        }
    }//GEN-LAST:event_txtEmailUserKeyReleased

    private void txtPassUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassUserKeyReleased
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            txtRepeatPassUser.requestFocus();
        }
    }//GEN-LAST:event_txtPassUserKeyReleased

    private void txtRepeatPassUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepeatPassUserKeyReleased
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            if (!txtPassUser.getText().equals(txtRepeatPassUser.getText())) {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden!");
            }
        }
    }//GEN-LAST:event_txtRepeatPassUserKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_userCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_userCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_userCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_userCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_userCrud dialog = new V_userCrud(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblTitleToMove;
    private javax.swing.JLabel lblTitleToMove1;
    private javax.swing.JLabel lblTitleToMove2;
    private javax.swing.JLabel lblTitleToMove3;
    private javax.swing.JLabel lblTitleToMove5;
    private javax.swing.JLabel lblTitleToMove6;
    private javax.swing.JLabel lblTitleToMove7;
    private javax.swing.JLabel lblTitleToMove8;
    private javax.swing.JScrollPane scplTableUsers;
    private javax.swing.JTable tbUsers;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtFirstNameUser;
    private javax.swing.JTextField txtLastNameUser;
    private javax.swing.JPasswordField txtPassUser;
    private javax.swing.JPasswordField txtRepeatPassUser;
    // End of variables declaration//GEN-END:variables
}
